Repository manaAghub/leetCode-Questions, pull requests merged in 2022-10, with the labels that each got.

#1 Create Detect_a_cycle_in_LindeList.cpp
  Detect_a_cycle_in_LindeList.cpp
Labels: good first issue, hacktoberfest-accepted

#2 binary search
  binarysearch.cpp
Labels: good first issue, hacktoberfest-accepted

#3 some more code added
  binarysearch.cpp
Labels: good first issue, hacktoberfest-accepted

#6 Create inorder_traversal_recursive.cpp
  inorder_traversal_recursive.cpp
Labels: enhancement, hacktoberfest-accepted

#5 01 knapsack added
  C++/0-1-knapsack-problem.cpp
  C++/egg-dropping-puzzle.cpp
Labels: good first issue, hacktoberfest-accepted

#7 Rename Detect_a_cycle_in_LindeList.cpp to Detect_a_cycle_in_LinkedLis…
  Detect_a_cycle_in_LinkedList.cpp
Labels: enhancement, hacktoberfest-accepted

#8 Create Starting_Point_of_loop_in_Linked_List.cpp
  Starting_Point_of_loop_in_Linked_List.cpp
Labels: enhancement, hacktoberfest-accepted

#10 Create morris_inorder_traversal.cpp
  morris_inorder_traversal.cpp
Labels: enhancement, hacktoberfest-accepted

#11 Add solution to Rotate a linkedlist problem
  Rotate_a_linked_list.cpp
Labels: enhancement, hacktoberfest-accepted

#12 Add solution to trapping Rainwater problem
  Trapping_Rainwater_problem.cpp
Labels: enhancement, hacktoberfest-accepted

#13 Create kth_largets_element_in_bst.cpp
  kth_largets_element_in_bst.cpp
Labels: enhancement, hacktoberfest-accepted

#14 cf code
  CF/1746problemB.cpp
Labels: enhancement, hacktoberfest-accepted

#17 created divisible numbers easy version
  divisible_number_easy.cpp
Labels: enhancement, hacktoberfest-accepted

#18 created boredom
  a_boredom.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#20 created jumping
  jumping_on_tiles.cpp
Labels: good first issue, hacktoberfest-accepted

#19 created scuza
  scuza.cpp
Labels: enhancement, hacktoberfest-accepted

#23 added contributing.md file
  CONTRIBUTING.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#24 elimination game added
  C++/elimination_game.cpp
Labels: enhancement, hacktoberfest-accepted

#25 Create Number of Islands.cpp
  C++/Number of Islands.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#27 Add Solution to Two Sum IV
  C++/Two_Sum_IV_Input_In_A_BST.cpp
Labels: good first issue, hacktoberfest-accepted

#28 Add Solution to Count Inversions
  C++/Count_Inversions.cpp
Labels: enhancement, hacktoberfest-accepted

#29 Add Solution to Vertical Order Traversal Of Binary Tree
  C++/22_Vertical_Traversal_Of_Binary_Tree.cpp
Labels: enhancement, hacktoberfest-accepted

#30 Create setmatrixzero.cpp
  setmatrixzero.cpp
Labels: documentation, hacktoberfest-accepted

#31 Add Solution to Union Of Linked List
  C++/Union_Of_Linked_List_CPP.cpp
Labels: enhancement, hacktoberfest-accepted

#36 Created 1363problemA file
  CF/1363problemA.cpp
Labels: good first issue, hacktoberfest-accepted

#35 Add Solution to Left View Of Binary Tree
  C++/Left_View_Of_Binary_Tree.cpp
Labels: enhancement, hacktoberfest-accepted

#34 Create kadane's_algorithm.cpp
  kadane's_algorithm.cpp
Labels: enhancement, hacktoberfest-accepted

#33 Create next_permutation.cpp
  next_permutation.cpp
Labels: enhancement, hacktoberfest-accepted

#37 Create 1553problemB.cpp
  CF/1553problemB.cpp
Labels: enhancement, hacktoberfest-accepted

#38 Create Sortanarrayof0's1's2's.cpp
  Sortanarrayof0's1's2's.cpp
Labels: enhancement, hacktoberfest-accepted

#32 Create Pascal's_triangle.cpp
  Pascal's_triangle.cpp
Labels: enhancement, hacktoberfest-accepted

#41 Create 1574problemC.cpp
  CF/1574problemC.cpp
Labels: documentation, hacktoberfest-accepted

#40 Add Solution to Palindrome Linked List
  C++/Palindrom_Linked_List.cpp
Labels: documentation, good first issue

#39 Create stockbuyandsell.cpp
  stockbuyandsell.cpp
Labels: enhancement, hacktoberfest-accepted

#42 Create 1744problemD.cpp
  CF/1744problemD.cpp
Labels: enhancement, hacktoberfest-accepted

#44 Create 1744problemD.cpp
  CF/1744problemD.cpp
Labels: enhancement, hacktoberfest-accepted

#46 Create n_queen_2.cpp
  n_queen_2.cpp
Labels: good first issue, hacktoberfest-accepted

#45 Add Solution to LCA of Binary Tree
  C++/Lowest_Common_Ancestor_In_Binary_Tree.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#48 Create ReverseALinkedList.cpp
  ReverseALinkedList.cpp
Labels: enhancement, hacktoberfest-accepted

#52 Create AddTwoNumbersAsLinkedlist.cpp
  AddTwoNumbersAsLinkedlist.cpp
Labels: enhancement, hacktoberfest-accepted

#51 Added functions for Linked List
  Graphs.java
  LinkedList.java
Labels: enhancement, hacktoberfest-accepted

#50 Create MergeTwoSortedLinkedlist.cpp
  MergeTwoSortedLinkedlist.cpp
Labels: enhancement, hacktoberfest-accepted

#47 Create text_justification.cpp
  text_justification.cpp
Labels: enhancement, hacktoberfest-accepted

#26 Largest_Rectangle_in_Histogram added
  C++/Largest_Rectangle_in_Histogram.cpp
Labels: enhancement

#49 Create FindmiddleelementinLinked List
  FindmiddleelementinLinked List
Labels: enhancement, hacktoberfest-accepted

#54 Create dungeon_game.cpp
  dungeon_game.cpp
Labels: enhancement, hacktoberfest-accepted

#53 Create binary_tree_maximum_path_sum.cpp
  binary_tree_maximum_path_sum.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#58 Create largest-rectangle-in-histogram.cpp
  largest-rectangle-in-histogram.cpp
Labels: enhancement, hacktoberfest-accepted

#57 Create shortest-path-in-a-grid-with-obstacles-elimination.cpp
  shortest-path-in-a-grid-with-obstacles-elimination.cpp
Labels: enhancement, hacktoberfest-accepted

#56 Create word_break_2.cpp
  word_break_2.cpp
Labels: good first issue, hacktoberfest-accepted

#55 Create the_skyline_problem.cpp
  the_skyline_problem.cpp
Labels: enhancement, hacktoberfest-accepted

#62 Created GroupAnagram.cpp file
  groupAnagram.cpp
Labels: enhancement, hacktoberfest-accepted

#63 Created Earliest.cpp
  Earliest.cpp
Labels: enhancement, hacktoberfest-accepted

#64 Created Oddstring.cpp
  Oddstring.cpp
Labels: enhancement, hacktoberfest-accepted

#65 Created WordsIntwoEdits.cpp file
  WordsIntwoEdits.cpp
Labels: enhancement, hacktoberfest-accepted

#68 Create MedianofTwoSortedArrays.cpp
  MedianofTwoSortedArrays.cpp
Labels: enhancement, hacktoberfest-accepted

#67 Create AggressiveCows.cpp
  AggressiveCows.cpp
Labels: enhancement, hacktoberfest-accepted

#70 Create AllocateMinimumNumberofPages.cpp
  AllocateMinimumNumberofPages.cpp
Labels: enhancement, hacktoberfest-accepted

#66 Create AddtwoNumbersAsLinkedlist.cpp
  AddtwoNumbersAsLinkedlist.cpp
Labels: enhancement, hacktoberfest-accepted
